### ISSUE TITLE
[DatePicker] Make possible to hide year view

### ISSUE THREAD

**Issue by LukasDeco** [mui/material-ui-pickers#1012]
Hi Material-UI-Pickers team! 

I love your date picker, but my app has a special use case.

My app allows people to set occasions for family and friends, like birthdays, holidays, etc. I don't want them to actually be able to select the year, just month and date. Once they select a month and date, the app will just take into account what today's date is and act accordingly.

So I really want a mode for the DatePicker component that only allows users to select day/month. Is this possible? I would love to contribute to the project and submit a PR for this if you would prefer.

Thanks!
Lukas

**Comment by dmtrKovalenko** [comment]
I see, for now it is not possible, we will extend `views` functionality to make it works as expected

**Comment by dmtrKovalenko** [comment]
Fixed in 3.0.0

**Comment by hilwat** [comment]
@dmtrKovalenko, I have a question is there a way to stagger the answers so it goes the year > then the month > then the day. Like this "Birthday date picker" - https://vuetifyjs.com/en/components/date-pickers

1. Unfilled out
<img width="839" alt="Screen Shot 2019-07-08 at 6 54 28 PM" src="https://user-images.githubusercontent.com/18738349/60847804-15975280-a1b2-11e9-98bd-7b2f2cf0e0d6.png">

2. Ask year <img width="449" alt="Screen Shot 2019-07-08 at 6 54 35 PM" src="https://user-images.githubusercontent.com/18738349/60847803-15975280-a1b2-11e9-8b27-7ec966c9fde4.png">

3. Ask Month
<img width="537" alt="Screen Shot 2019-07-08 at 6 54 44 PM" src="https://user-images.githubusercontent.com/18738349/60847802-15975280-a1b2-11e9-8039-cc8bff1ec4d5.png">

4. Ask Date
<img width="518" alt="Screen Shot 2019-07-08 at 6 54 52 PM" src="https://user-images.githubusercontent.com/18738349/60847801-15975280-a1b2-11e9-8922-987b49aea336.png">

5. Filled out
<img width="836" alt="Screen Shot 2019-07-08 at 6 54 57 PM" src="https://user-images.githubusercontent.com/18738349/60847800-15975280-a1b2-11e9-90fd-f3647b3377a4.png">

I can get it to open to Year but can't find a way to get the month step in? Would love to know how. THANK YOU SO MUCH 🙏

**Comment by hilwat** [comment]
@dmtrKovalenko @LukasDeco 
Maybe "Dynamic Data" is a work around? 
https://material-ui-pickers.dev/demo/datepicker

<img width="1109" alt="Screen Shot 2019-07-08 at 7 30 54 PM" src="https://user-images.githubusercontent.com/18738349/60849041-036be300-a1b7-11e9-8a58-66f53e747c99.png">

**Comment by LukasDeco** [comment]
I know this is marked as closed, but I still don't see the datepicker hiding the year from the view when I use : `views={['month', 'date']}`

Is there something I am missing?

**Comment by psamim** [comment]
@dmtrKovalenko Me too. I do not see the effect of `views` prop on the date picker. Any other things needs to be configured?

**Comment by TomekStaszkiewicz** [comment]
Hello! I know that almost a year has passed since the last comments, but I try to use `views={['month', 'date']}` but it does not work as expected. I can still see the year there :( How can I create a picker with only month and day selectable? Did you manage to solve that issue @LukasDeco @psamim ?

**Comment by oliviertassinari** [comment]
@TomekStaszkiewicz Do you have a reproduction with v4.0.0-alpha.8? Do you want to open a new issue?

**Comment by sdankel** [comment]
Could we reopen this? This is not fixed. The repro is simple:

```
    <LocalizationProvider dateAdapter={AdapterLuxon}>
        <DatePicker
          views={['month', 'day']}
          label="Month and Day"
          minDate={'01-01'}
          maxDate={'12-31'}
          value={value}
          onChange={(newValue: string | null) => {
            setValue(newValue);
          }}
          renderInput={(params:any) => {
          return <TextField {...params} helperText={null} />;
          }}
        />
</LocalizationProvider>
```

This shows the current year by default. Expected: No year shown.

**Comment by alexfauquette** [comment]
@sdankel The issue is about allowing to hide the year view (a view where years from minDate to maxDate are listed)

From your example, I assume you expect to hidde the year in the input. Which can be done with the `inputFormat` prop

`inputFormat="MM-dd"`
https://codesandbox.io/s/peaceful-water-ptyrdc?file=/demo.tsx

**Comment by sdankel** [comment]
> @sdankel The issue is about allowing to hide the year view (a view where years from minDate to maxDate are listed)
> 
> From your example, I assume you expect to hidde the year in the input. Which can be done with the `inputFormat` prop
> 
> `inputFormat="MM-dd"` https://codesandbox.io/s/peaceful-water-ptyrdc?file=/demo.tsx

Thanks for sharing the sandbox, @alexfauquette 

This is a screenshot from the sandbox: 
![image](https://user-images.githubusercontent.com/47993817/214222054-c3ff93f1-e50b-4690-ab5d-a4007d49f7c0.png)

You can see that the year still shows up when you click on it. My hope is to have a date picker that is year-less.

**Comment by LukasTy** [comment]
@sdankel You are referring to the calendar header and ability of changing it.
We have an issue ready for it: https://github.com/mui/mui-x/issues/6653
We just need to find time to tackle it. 👌

**Comment by alexfauquette** [comment]
By the way @sdankel you're on `material-ui-pickers` repository. To get the improvements, you will have to migrate to `@mui/x-date-pickers` which is has currently a v5 stable and the v6 is on the road (currently in beta phase)
